#!/bin/sh

. legit-setup.sh

# If we don't have a tracking branch, we must make one
if git show-ref --quiet refs/tracking/main
then
    die "Tracking Branch Already Exists"
else
    empty_tree=$(echo "" | git mktree --batch)
    empty_file=$(printf "" | git hash-object -w --stdin)

    proposals=$(
    {
        echo 100644 blob $empty_file$'\t'open
        echo 100644 blob $empty_file$'\t'pending
    } | git mktree --missing)

    tracking=$(
    {
        echo 100644 blob $empty_file$'\t'config
        echo 040000 tree $empty_tree$'\t'users
        echo 040000 tree $proposals$'\t'proposals
    } | git mktree --missing)

    tracking=$(git commit-tree -m "Legitimised Repository" $tracking)

    git update-ref refs/tracking/main $tracking
fi